name: Publish Nuget

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore source/Iciclecreek.Avalonia.WindowManager/Iciclecreek.Avalonia.WindowManager.csproj 
 
      - name: Build
        run: dotnet build --no-restore source/Iciclecreek.Avalonia.WindowManager/Iciclecreek.Avalonia.WindowManager.csproj -c Release --property WarningLevel=0

      - name: dotnet pack 
        run: |
          dotnet pack --no-build source/Iciclecreek.Avalonia.WindowManager/Iciclecreek.Avalonia.WindowManager.csproj -c Release -o packages --include-symbols --property WarningLevel=0

      - name: Publish NuGet and symbols
        id: nuget-push
        uses: edumserrano/nuget-push@v1.2.2
        with:
          api-key: '${{ secrets.NUGET_KEY }}' 
          working-directory: 'packages'
          fail-if-exists: false

      
